# Generates the three assets the NSIS script needs but can't consume directly:
#   installer.bmp - the welcome/finish image, drawn from res/app.png (NSIS can't
#                   use PNG; it wants a 164x314 BMP).
#   readme.rtf    - README.md converted to RTF for the About page (NSIS can't
#                   render Markdown, but its RichEdit control renders RTF).
#   version.nsh   - the crate version, so the installer can state which version
#                   it installs without a second copy to keep in sync by hand.
# Called by build-installer.bat. Kept ASCII-only (glyph patterns use \uXXXX) so
# Windows PowerShell 5.1, which reads .ps1 as the system codepage, parses it.

param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')),
    [string]$Out  = $PSScriptRoot,

    # Leave installer.bmp alone. Drawing it needs System.Drawing, which .NET
    # only has on Windows, so off Windows this is on regardless - that is
    # enough to regenerate and check readme.rtf from Linux.
    [switch]$SkipBitmap
)
$ErrorActionPreference = 'Stop'
if (-not (($PSVersionTable.PSEdition -eq 'Desktop') -or $IsWindows)) { $SkipBitmap = $true }

# --- version.nsh from Cargo.toml ---
# The wizard shows the version it is installing, so it must never drift from the
# crate version. [package] is the first table in Cargo.toml and dependencies
# spell their versions inline, so the first line-anchored `version =` is ours.
$cargo = Get-Content -Raw -Encoding UTF8 (Join-Path $Root 'Cargo.toml')
$m = [regex]::Match($cargo, '(?m)^\s*version\s*=\s*"([^"]+)"')
if (-not $m.Success) { throw "no [package] version found in Cargo.toml" }
$ver = $m.Groups[1].Value

# VIProductVersion demands exactly four numeric components, so pad the dotted
# numeric prefix out to four and drop any pre-release suffix.
$parts = [System.Collections.ArrayList]@([regex]::Match($ver, '^\d+(\.\d+)*').Value -split '\.')
while ($parts.Count -lt 4) { [void]$parts.Add('0') }
$fileVer = ($parts[0..3]) -join '.'

[System.IO.File]::WriteAllText(
    (Join-Path $Out 'version.nsh'),
    "; Generated by make-assets.ps1 from Cargo.toml - do not edit.`r`n" +
    "!define VER `"$ver`"`r`n!define VER_FILE `"$fileVer`"`r`n",
    (New-Object System.Text.ASCIIEncoding))

# --- installer.bmp from app.png ---
if (-not $SkipBitmap) {
Add-Type -AssemblyName System.Drawing
$png = [System.Drawing.Image]::FromFile((Join-Path $Root 'res\app.png'))
$bmp = New-Object System.Drawing.Bitmap 164, 314
$g   = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::FromArgb(24, 24, 24))
$g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$g.DrawImage($png, 22, 44, 120, 120)
$font = New-Object System.Drawing.Font('Segoe UI', 15, [System.Drawing.FontStyle]::Bold)
$g.DrawString('NanoTorrent', $font, [System.Drawing.Brushes]::White, 12, 178)
$font.Dispose(); $g.Dispose()
$bmp.Save((Join-Path $Out 'installer.bmp'), [System.Drawing.Imaging.ImageFormat]::Bmp)
$png.Dispose(); $bmp.Dispose()
}

# --- readme.rtf from README.md ---
# RTF, not plain text: the RichEdit control NSIS uses for that page renders RTF
# directly, and RTF is pure 7-bit ASCII on disk - every non-ASCII character
# becomes a \uNNNN? escape. That sidesteps the encoding guess that mangled the
# em dashes / arrows in the old readme.txt, and gives real formatting.
#
# README.md is written for GitHub, so it carries things a RichEdit control has
# no use for: <img> tags and ![images], a screenshot gallery laid out as a
# table, <sub> captions. Those are taken out or reduced to their text here
# rather than shown as markup - which is what the installer used to do.

# The HTML tags README.md is allowed to use, removed with their text kept.
# Named rather than "anything in angle brackets": prose and code spans use
# <ver>, <hash> and friends as placeholders, and those have to survive.
$HtmlTags = 'img|sub|sup|br|p|div|span|picture|source|a|b|i|em|strong|kbd|details|summary|center'

# Inline markup -> RTF, for text outside code spans. Order matters: images,
# links and tags are removed from the raw text, then RTF's own specials are
# escaped, and only then are control words inserted, so they survive.
function ConvertTo-RtfText([string]$s) {
    $s = [regex]::Replace($s, '!\[[^\]]*\]\([^)]*\)', '')                 # ![alt](src) -> nothing
    $s = [regex]::Replace($s, "</?(?:$HtmlTags)\b[^>]*>", '')              # <img ...>, <sub> -> nothing
    $s = [regex]::Replace($s, '\[([^\]]+)\]\([^)]+\)', '$1')              # [text](url) -> text
    $s = [regex]::Replace($s, '<((?:https?|mailto):[^>]+)>', '$1')
    $s = $s.Replace('\', '\\').Replace('{', '\{').Replace('}', '\}')
    $s = [regex]::Replace($s, '\*\*([^*]+)\*\*', '{\b $1}')
    # One star, hugging its text on both sides - so "a * b" and a bare "*"
    # stay as they are.
    $s = [regex]::Replace($s, '(?<![*\w])\*(?=\S)([^*]+?)(?<=\S)\*(?![*\w])', '{\i $1}')
    $s
}

# A whole line of inline Markdown. Code spans are swapped for placeholders
# first, so nothing inside backticks is read as markup - `lang/*.json` keeps
# its star and `<ver>` its brackets - and put back last. Placeholders rather
# than splitting the line at them: bold that CONTAINS a code span, like
# **the `.torrent` files**, has to stay one bold run.
function ConvertTo-RtfInline([string]$s) {
    $codes = New-Object System.Collections.ArrayList
    $s = [regex]::Replace($s, '`([^`]+)`', [System.Text.RegularExpressions.MatchEvaluator] {
            param($m)
            "$([char]1)$($codes.Add($m.Groups[1].Value))$([char]2)"
        })
    $s = ConvertTo-RtfText $s
    $s = [regex]::Replace($s, '\x01(\d+)\x02', [System.Text.RegularExpressions.MatchEvaluator] {
            param($m)
            $code = [string]$codes[[int]$m.Groups[1].Value]
            '{\f1 ' + $code.Replace('\', '\\').Replace('{', '\{').Replace('}', '\}') + '}'
        })
    $s.Trim()
}

# Non-ASCII -> \uNNNN? (\uc1 in the header says one fallback char follows).
function ConvertTo-RtfAscii([string]$s) {
    $sb = New-Object System.Text.StringBuilder
    foreach ($ch in $s.ToCharArray()) {
        $c = [int]$ch
        if ($c -gt 127) { [void]$sb.Append('\u').Append($c).Append('?') }
        else            { [void]$sb.Append($ch) }
    }
    $sb.ToString()
}

# Sizes are in half-points: 18 is 9pt, the body text. Every paragraph resets to
# it with \plain rather than trusting the previous one to have cleaned up -
# a size left behind by one heading is how the whole page after it comes out
# the wrong size.
$Body = '\plain\f0\fs18'

$rtf = New-Object System.Text.StringBuilder
[void]$rtf.AppendLine('{\rtf1\ansi\ansicpg1252\deff0\uc1')
[void]$rtf.AppendLine('{\fonttbl{\f0\fswiss\fcharset0 Segoe UI;}{\f1\fmodern\fcharset0 Consolas;}}')
[void]$rtf.AppendLine("\viewkind4$Body")

# -Encoding UTF8 is REQUIRED: PowerShell 5.1's Get-Content defaults to the
# system ANSI codepage, which turns every em dash into "a<euro>" mojibake
# before any of the conversion below runs.
$lines = (Get-Content -Raw -Encoding UTF8 (Join-Path $Root 'README.md')) -split "\r?\n"

# Pass 1: fold Markdown's hard-wrapped lines into logical blocks, so a bullet,
# quote or paragraph that spans three source lines stays ONE RTF paragraph.
$blocks = New-Object System.Collections.ArrayList
$inCode = $false
$cur = $null
function Close-Block { if ($script:cur) { [void]$script:blocks.Add($script:cur); $script:cur = $null } }

foreach ($line in $lines) {
    if ($line -match '^\s*```') {
        Close-Block
        $inCode = -not $inCode
        continue
    }
    if ($inCode)                    { Close-Block; [void]$blocks.Add(@{ Kind = 'code';  Text = $line }); continue }
    if ($line -match '^\s*$')       { Close-Block; continue }
    if ($line -match '^\s*\|')      { Close-Block; [void]$blocks.Add(@{ Kind = 'table'; Text = $line.Trim() }); continue }
    if ($line -match '^(#{1,6})\s+(.*)') {
        Close-Block
        [void]$blocks.Add(@{ Kind = "h$($Matches[1].Length)"; Text = $Matches[2].Trim() })
        continue
    }
    if ($line -match '^\s*>\s?(.*)') {
        # A quote runs on over its `>` lines rather than one paragraph each.
        if ($cur -and $cur.Kind -eq 'quote') { $cur.Text += ' ' + $Matches[1].Trim() }
        else { Close-Block; $cur = @{ Kind = 'quote'; Text = $Matches[1].Trim() } }
        continue
    }
    if ($line -match '^(\s*)[-*]\s+(.*)') {
        Close-Block
        # Two spaces of indent per level, as README.md is written.
        $level = [Math]::Min([int][Math]::Floor($Matches[1].Length / 2), 2)
        $cur = @{ Kind = 'bullet'; Text = $Matches[2].Trim(); Level = $level }
        continue
    }
    # Anything else continues the open block, or starts a paragraph.
    if ($cur) { $cur.Text += ' ' + $line.Trim() } else { $cur = @{ Kind = 'para'; Text = $line.Trim() } }
}
Close-Block

# Pass 2: blocks -> RTF.
$tableHeader = $null
foreach ($b in $blocks) {
    if ($b.Kind -ne 'table') { $tableHeader = $null }

    # Headings, paragraphs and the like that were only an image or a tag have
    # nothing left to show, and an empty paragraph is only a gap.
    if ($b.Kind -ne 'code' -and $b.Kind -ne 'table') {
        $text = ConvertTo-RtfInline $b.Text
        if (-not $text) { continue }
    }

    switch ($b.Kind) {
        'code' {
            $code = $b.Text.Replace('\', '\\').Replace('{', '\{').Replace('}', '\}')
            [void]$rtf.AppendLine("\pard\li280\sa0$Body\f1\fs16 $code\par")
        }
        'table' {
            $cells = @(($b.Text -replace '^\||\|$', '') -split '\s*\|\s*' | ForEach-Object { ConvertTo-RtfInline $_ })
            # The separator row (|---|---|) is dropped.
            if (($b.Text -replace '[|\s]', '') -match '^[-:]*$' -and $b.Text -match '-') { break }
            if ($null -eq $tableHeader) { $tableHeader = $cells; break }

            if (-not ($tableHeader -join '')) {
                # No header at all: a layout table, like the screenshot gallery -
                # rows of pictures with a row of captions under each. With the
                # pictures gone, each caption is simply a paragraph.
                foreach ($cell in $cells) {
                    if ($cell) { [void]$rtf.AppendLine("\pard\sa80$Body $cell\par") }
                }
                break
            }

            # A real table. The header row labels each cell, so a wide
            # comparison table still reads top-to-bottom in a narrow window.
            # ponytail: label-per-cell instead of a real RTF \trowd table -
            # upgrade if a table ever needs to be read column-wise.
            [void]$rtf.AppendLine("\pard\sa40$Body{\b $($cells[0])}\par")
            for ($i = 1; $i -lt $cells.Count; $i++) {
                $label = if ($i -lt $tableHeader.Count) { $tableHeader[$i] } else { '' }
                [void]$rtf.AppendLine("\pard\li280\sa40$Body{\i $label}:  $($cells[$i])\par")
            }
        }
        'h1'     { [void]$rtf.AppendLine("\pard\sb120\sa120$Body{\b\fs32 $text}\par") }
        'h2'     { [void]$rtf.AppendLine("\pard\sb160\sa100$Body{\b\fs26 $text}\par") }
        'h3'     { [void]$rtf.AppendLine("\pard\sb100\sa80$Body{\b\fs21 $text}\par") }
        'quote'  { [void]$rtf.AppendLine("\pard\li280\sa80$Body{\i $text}\par") }
        'bullet' {
            # A hanging indent with a tab stop AT the indent: the bullet sits in
            # the gap and the text lines up with its own wrapped lines. Without
            # the \tx the tab jumps to the next default stop, half an inch on,
            # and the first line starts well to the right of the rest.
            $indent = 360 * ($b.Level + 1)
            $mark = if ($b.Level -eq 0) { '\bullet' } else { '\endash' }
            [void]$rtf.AppendLine("\pard\li$indent\fi-240\tx$indent\sa60$Body $mark\tab $text\par")
        }
        'para'   { [void]$rtf.AppendLine("\pard\sa80$Body $text\par") }
        default  { [void]$rtf.AppendLine("\pard\sb80\sa60$Body{\b $text}\par") }   # h4-h6
    }
}

[void]$rtf.AppendLine('}')

# ASCII-only output, so no BOM and no codepage guessing anywhere in the chain.
[System.IO.File]::WriteAllText(
    (Join-Path $Out 'readme.rtf'),
    (ConvertTo-RtfAscii $rtf.ToString()),
    (New-Object System.Text.ASCIIEncoding))

if ($SkipBitmap) {
    Write-Host "Generated version.nsh ($ver) and readme.rtf (installer.bmp skipped)"
} else {
    Write-Host "Generated version.nsh ($ver), installer.bmp and readme.rtf"
}
