; NanoTorrent NSIS installer.
; Compiled by build-installer.bat (which also generates installer.bmp from
; res/app.png, readme.rtf from README.md, and version.nsh from Cargo.toml).
; Requires NSIS 3.x.

Unicode true
!include "MUI2.nsh"

; VER / VER_FILE, generated from Cargo.toml by make-assets.ps1 - the wizard
; states the version it installs, so it must not be a second hand-kept copy.
!include "version.nsh"

!define APP "NanoTorrent"
; The GUI. Every shortcut and file association points here, so an
; ordinary launch never opens a console window.
!define EXE "nanotorrent-gui.exe"
; The console-subsystem launcher, and the one a shell finds when you
; type `nanotorrent`. It forwards argv to the GUI binary and waits, which
; is the only way cmd/PowerShell will wait too. See src/bin/console.rs.
!define CLI_EXE "nanotorrent-cli.exe"
; Installed a second time under the bare name, so the command the docs
; and the program's own --help text use - `nanotorrent` - resolves.
!define CLI_ALIAS "nanotorrent.exe"
!define PUBLISHER "Power2All"
!define UNINSTKEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP}"

; Versioned: MUI substitutes this into the caption and the Welcome / Finish /
; uninstall-confirm page headings, so every screen says which version this is.
Name "${APP} ${VER}"
OutFile "${APP}-${VER}-Setup.exe"
InstallDir "$PROGRAMFILES64\${APP}"
InstallDirRegKey HKLM "Software\${APP}" "InstallDir"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

VIProductVersion "${VER_FILE}"
VIAddVersionKey "ProductName" "${APP}"
VIAddVersionKey "FileVersion" "${VER}"
VIAddVersionKey "ProductVersion" "${VER}"
VIAddVersionKey "FileDescription" "${APP} Setup"
VIAddVersionKey "LegalCopyright" "${PUBLISHER}"

; --- Branding: app.png (converted to installer.bmp) + app.ico ---
!define MUI_ICON "..\res\app.ico"
!define MUI_UNICON "..\res\app.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "installer.bmp"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "installer.bmp"

; --- README shown as a scrollable INFORMATION page ---
; MUI has no dedicated readme page, so this is the license page with the
; agreement framing removed: header/subheader retitled, no "I Agree" wording,
; nothing to accept. The content is readme.rtf (RTF, generated by
; make-assets.ps1) - the page's RichEdit control renders it as formatted text.
!define MUI_PAGE_HEADER_TEXT "About ${APP}"
!define MUI_PAGE_HEADER_SUBTEXT "What you are about to install."
!define MUI_LICENSEPAGE_TEXT_TOP "Scroll to read, then click Next to continue."
!define MUI_LICENSEPAGE_TEXT_BOTTOM " "
!define MUI_LICENSEPAGE_BUTTON "Next"

!define MUI_FINISHPAGE_RUN "$INSTDIR\${EXE}"
!define MUI_FINISHPAGE_RUN_TEXT "Launch ${APP}"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "readme.rtf"
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; The Microsoft Store package family name. Partner Center issues it alongside
; the identity substituted into installer/msix/AppxManifest.xml, and it is
; stable for the life of the listing - the version is not part of it.
!define STORE_PFN "Power2All.NanoTorrent_jsrm4ke13n4c4"

; Warn before installing beside a Microsoft Store copy.
;
; The two are separate installs. This installer cannot upgrade an MSIX package;
; it can only put a second ${APP} on the machine, with its own settings folder
; and its own Start menu entry, and no way to tell afterwards which one a
; shortcut launches. ${APP} itself now sends a Store build to the Store rather
; than to the GitHub release page (see updatechecker::download_url), so this
; catches whoever arrives here from the website by hand.
;
; $LOCALAPPDATA\Packages\<family name> is created when a package is deployed
; for a user, so its presence is the test. It reads the profile of whoever was
; elevated, which is not necessarily the person with the Store install - hence
; a question rather than a refusal.
Function .onInit
  IfFileExists "$LOCALAPPDATA\Packages\${STORE_PFN}\*.*" 0 no_store_copy
    MessageBox MB_YESNO|MB_ICONEXCLAMATION "${APP} is already installed from the Microsoft Store.$\n$\nThis installer cannot update that copy - it installs a second ${APP} alongside it, with separate settings.$\n$\nUpdate from the Microsoft Store instead.$\n$\nInstall anyway?" IDYES no_store_copy
    Abort
  no_store_copy:
FunctionEnd

Section "!${APP} (required)" SecCore
  SectionIn RO
  SetOutPath "$INSTDIR"
  ; The lang/*.json files are compiled into the exe (see build.rs), so there is
  ; no lang folder to install. Dropping one next to the exe still overrides a
  ; locale at runtime.
  File "/oname=${EXE}" "..\target\release\nanotorrent-gui.exe"
  File "/oname=${CLI_EXE}" "..\target\release\nanotorrent-cli.exe"
  File "/oname=${CLI_ALIAS}" "..\target\release\nanotorrent-cli.exe"

  CreateDirectory "$SMPROGRAMS\${APP}"
  CreateShortcut "$SMPROGRAMS\${APP}\${APP}.lnk" "$INSTDIR\${EXE}"
  CreateShortcut "$SMPROGRAMS\${APP}\Uninstall ${APP}.lnk" "$INSTDIR\uninstall.exe"

  WriteUninstaller "$INSTDIR\uninstall.exe"
  WriteRegStr HKLM "Software\${APP}" "InstallDir" "$INSTDIR"

  WriteRegStr HKLM "${UNINSTKEY}" "DisplayName" "${APP}"
  WriteRegStr HKLM "${UNINSTKEY}" "DisplayVersion" "${VER}"
  WriteRegStr HKLM "${UNINSTKEY}" "Publisher" "${PUBLISHER}"
  WriteRegStr HKLM "${UNINSTKEY}" "DisplayIcon" "$INSTDIR\${EXE},0"
  WriteRegStr HKLM "${UNINSTKEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKLM "${UNINSTKEY}" "InstallLocation" "$INSTDIR"
  WriteRegDWORD HKLM "${UNINSTKEY}" "NoModify" 1
  WriteRegDWORD HKLM "${UNINSTKEY}" "NoRepair" 1
SectionEnd

Section "Set as default for .torrent files and magnet links" SecAssoc
  ; .torrent ProgID + extension
  WriteRegStr HKLM "Software\Classes\${APP}.Torrent" "" "BitTorrent Document"
  WriteRegStr HKLM "Software\Classes\${APP}.Torrent\DefaultIcon" "" "$INSTDIR\${EXE},0"
  WriteRegStr HKLM "Software\Classes\${APP}.Torrent\shell\open\command" "" '"$INSTDIR\${EXE}" "%1"'
  WriteRegStr HKLM "Software\Classes\.torrent" "" "${APP}.Torrent"
  WriteRegStr HKLM "Software\Classes\.torrent" "Content Type" "application/x-bittorrent"
  WriteRegStr HKLM "Software\Classes\.torrent\OpenWithProgids" "${APP}.Torrent" ""

  ; magnet ProgID + protocol handler
  WriteRegStr HKLM "Software\Classes\${APP}.Magnet" "" "Magnet URI"
  WriteRegStr HKLM "Software\Classes\${APP}.Magnet" "URL Protocol" ""
  WriteRegStr HKLM "Software\Classes\${APP}.Magnet\DefaultIcon" "" "$INSTDIR\${EXE},0"
  WriteRegStr HKLM "Software\Classes\${APP}.Magnet\shell\open\command" "" '"$INSTDIR\${EXE}" "%1"'
  WriteRegStr HKLM "Software\Classes\magnet" "" "URL:magnet protocol"
  WriteRegStr HKLM "Software\Classes\magnet" "URL Protocol" ""
  WriteRegStr HKLM "Software\Classes\magnet\shell\open\command" "" '"$INSTDIR\${EXE}" "%1"'

  ; Application capabilities so it appears in Settings > Default apps and is
  ; OFFERED for both the file type and the protocol.
  WriteRegStr HKLM "Software\${APP}\Capabilities" "ApplicationName" "${APP}"
  WriteRegStr HKLM "Software\${APP}\Capabilities" "ApplicationDescription" "A tiny, hackable BitTorrent client."
  WriteRegStr HKLM "Software\${APP}\Capabilities\FileAssociations" ".torrent" "${APP}.Torrent"
  WriteRegStr HKLM "Software\${APP}\Capabilities\URLAssociations" "magnet" "${APP}.Magnet"
  WriteRegStr HKLM "Software\RegisteredApplications" "${APP}" "Software\${APP}\Capabilities"

  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, i 0, i 0)'
SectionEnd

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecCore} "The ${APP} program (translations are built in)."
  !insertmacro MUI_DESCRIPTION_TEXT ${SecAssoc} "Register ${APP} for .torrent files and magnet: links. Windows may still ask you to confirm the default the first time."
!insertmacro MUI_FUNCTION_DESCRIPTION_END

Section "Uninstall"
  Delete "$INSTDIR\${EXE}"
  Delete "$INSTDIR\${CLI_EXE}"
  Delete "$INSTDIR\${CLI_ALIAS}"
  Delete "$INSTDIR\uninstall.exe"
  RMDir /r "$INSTDIR\lang"
  RMDir "$INSTDIR"

  Delete "$SMPROGRAMS\${APP}\${APP}.lnk"
  Delete "$SMPROGRAMS\${APP}\Uninstall ${APP}.lnk"
  RMDir "$SMPROGRAMS\${APP}"

  ; Only drop the shared .torrent / magnet defaults if they still point to us.
  ReadRegStr $0 HKLM "Software\Classes\.torrent" ""
  StrCmp $0 "${APP}.Torrent" 0 +2
    DeleteRegValue HKLM "Software\Classes\.torrent" ""
  ReadRegStr $0 HKLM "Software\Classes\magnet\shell\open\command" ""
  StrCmp $0 '"$INSTDIR\${EXE}" "%1"' 0 +2
    DeleteRegKey HKLM "Software\Classes\magnet\shell"

  DeleteRegKey HKLM "Software\Classes\${APP}.Torrent"
  DeleteRegKey HKLM "Software\Classes\${APP}.Magnet"
  DeleteRegValue HKLM "Software\RegisteredApplications" "${APP}"
  DeleteRegKey HKLM "Software\${APP}"
  DeleteRegKey HKLM "${UNINSTKEY}"
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, i 0, i 0)'
SectionEnd
